spring:
  main:
    allow-bean-definition-overriding: true

  # 使用springboot默认的hikari数据库连接池，配置比较简单明了
  datasource:
    common: &ds_common
      minimun-idle: 5
      maximum-pool-size: 15
      max-life-time: 600000
      idle-timeout: 300000
      validation-timeout: 5000
      connection-timeout: 5000
    #门架原始数据查询数据库
    main:
      <<: *ds_common
      pool-name: mainDataSource
      jdbc-url: jdbc:mysql:///main?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      connection-test-query: select 1
    slave:
      <<: *ds_common
      pool-name: slaveDataSource
      jdbc-url: jdbc:mysql:///slave?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      connection-test-query: select 1


  jpa:
    common: &jpa_common
      show-sql: true
      generate-ddl: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
    mysql:
      <<: *jpa_common
      database: mysql
      database-platform: org.hibernate.dialect.MySQL57Dialect
#      非jta事务
  jta:
    enabled: false

logging:
  file:
    path: D:\cstc\logs\audit-collect
#    调试所需
#  level:
#    org:
#      hibernate: trace

server:
  port: 8888
